### ISSUE TITLE
Building Laghos on Crusher

### ISSUE THREAD

**Issue by wyphan** [CEED/Laghos#172]
I'm currently in the process of "upgrading" the examples in the [HPCToolkit tutorial examples repo](https://github.com/HPCToolkit/hpctoolkit-tutorial-examples/pull/8), which includes Laghos. How do I build Laghos for AMD GPUs on Crusher (notably, the flags to pass onto `MFEM_BUILD`)?

**Comment by vladotomov** [comment]
Hi @wyphan, sorry for the late reply. Do you still need help with this?

**Comment by wyphan** [comment]
Yes, please, it will be used for Crusher at ORNL.

**Comment by v-dobrev** [comment]
For a parallel HIP build of MFEM on Crusher, you can try using `"MFEM_BUILD=phip HIP_ARCH=gfx90a"`.

**Comment by vladotomov** [comment]
@wyphan, did Veselin's suggestion help? Can we close this issue?

**Comment by wyphan** [comment]
@vladotomov sorry for the late reply. When I tried to build, looks like the URL for METIS in the Makefile is dead?

**Comment by vladotomov** [comment]
@wyphan the link to METIS has been updated.

**Comment by wyphan** [comment]
Thanks for the fix. METIS 4.0.3 builds fine with `PrgEnv-amd` and `amd/5.2.0`, but not with 5.3.0 or newer. For reference, the current default ROCm version on Crusher is 5.3.0. The error messages have to do with the `GKfree` macro:
```shell
make[3]: Entering directory '/autofs/nccs-svm1_home1/wyphan/work/hpctoolkit-tutorial-examples/examples/gpu/laghos/laghos/metis-4.0.3/Lib'
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
cc  -O2 -I. -c coarsen.c
cc  -O2 -I. -c fm.c
cc  -O2 -I. -c initpart.c
initpart.c:199:3: error: call to undeclared function '__GKfree'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  GKfree(&bestwhere, &queue, &touched, LTERM);
  ^
./rename.h:380:19: note: expanded from macro 'GKfree'
#define GKfree                          __GKfree
                                        ^
initpart.c:337:3: error: call to undeclared function '__GKfree'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  GKfree(&bestwhere, &queue, &touched, LTERM);
  ^
./rename.h:380:19: note: expanded from macro 'GKfree'
#define GKfree                          __GKfree
                                        ^
initpart.c:417:3: error: call to undeclared function '__GKfree'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  GKfree(&bestwhere, &perm, LTERM);
  ^
./rename.h:380:19: note: expanded from macro 'GKfree'
#define GKfree                          __GKfree
                                        ^
3 errors generated.
make[3]: *** [Makefile:21: initpart.o] Error 1
make[3]: Leaving directory '/autofs/nccs-svm1_home1/wyphan/work/hpctoolkit-tutorial-examples/examples/gpu/laghos/laghos/metis-4.0.3/Lib'
make[2]: *** [Makefile:4: default] Error 2
make[2]: Leaving directory '/autofs/nccs-svm1_home1/wyphan/work/hpctoolkit-tutorial-examples/examples/gpu/laghos/laghos/metis-4.0.3'
make[1]: *** [makefile:267: metis] Error 2
make[1]: Leaving directory '/autofs/nccs-svm1_home1/wyphan/work/hpctoolkit-tutorial-examples/examples/gpu/laghos/laghos/Laghos'
make[1]: Entering directory '/autofs/nccs-svm1_home1/wyphan/work/hpctoolkit-tutorial-examples/examples/gpu/laghos/laghos/Laghos'
makefile:132: *** The MFEM library is not built.  Stop.
make[1]: Leaving directory '/autofs/nccs-svm1_home1/wyphan/work/hpctoolkit-tutorial-examples/examples/gpu/laghos/laghos/Laghos'
```

**Comment by v-dobrev** [comment]
You can add the flag `-std=c89` to fix this.

**Comment by wyphan** [comment]
Perfect! Now Laghos builds cleanly on Crusher. Thanks a lot!
